name: CI/CD Pipeline for Covid X-ray CNN

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install tensorflow pandas numpy matplotlib seaborn opencv-python scikit-learn kaggle

    - name: Download dataset
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      run: |
        mkdir -p ~/.kaggle
        echo "{\"username\":\"$KAGGLE_USERNAME\",\"key\":\"$KAGGLE_KEY\"}" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json
        kaggle datasets download -d paultimothymooney/chest-xray-pneumonia
        unzip chest-xray-pneumonia.zip -d data/

    - name: Train the model
      run: python covid_x_ray_cnn_project_(1).py

    - name: Upload model artifacts
      uses: actions/upload-artifact@v3
      with:
        name: trained-model
        path: best_weights.weights.h5
